spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projecttest
    username: root
    password: qinyuqin
mybatis:
  type-aliases-package: com.bhinfocenter.project.pojo
  mapper-locations: classpath:mapper/*.xml
